# Generated by Django 5.2.8 on 2025-11-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='Panadería', max_length=50)),
                ('titulo', models.CharField(help_text='Ej: FICHA TÉCNICA TREKKING BREAD JUMBO UN', max_length=150, verbose_name='Nombre ficha / producto')),
                ('codigo', models.CharField(help_text='Ej: 3514-D-PAN-058', max_length=30, verbose_name='Código documento')),
                ('version', models.CharField(default='000', max_length=10, verbose_name='Versión')),
                ('fecha_revision', models.DateField(verbose_name='Fecha de revisión')),
                ('pagina', models.CharField(blank=True, max_length=20, verbose_name='Página')),
                ('kg_producidos_receta', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Kg producidos en base a receta')),
                ('kg_rendimiento_final', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Kg rendimiento final')),
                ('unidades_rendimiento_final', models.PositiveIntegerField(verbose_name='Unidades rendimiento final')),
                ('descripcion_proceso', models.TextField(verbose_name='Descripción detallada del proceso')),
                ('temperatura_horneado_c', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temperatura de horneo (°C)')),
                ('tiempo_horneado_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de horneo (min)')),
                ('temperatura_almacenamiento', models.CharField(blank=True, help_text='Ej: Temperatura ambiente, Cámara de frío, etc.', max_length=100, verbose_name='Temperatura de almacenamiento')),
                ('vida_util_camara_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vida útil en cámara (días)')),
                ('vida_util_sala_ventas_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vida útil en sala de ventas (días)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales / advertencias')),
                ('harina_base_kg', models.DecimalField(decimal_places=2, help_text='Harina usada en la receta base (ej: 16.00 kg)', max_digits=6, verbose_name='Harina base (kg) para cálculo')),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: ETIQUETA DIGI 12.3 x 5.7 cm', max_length=150, verbose_name='Descripción')),
                ('unidad', models.CharField(help_text='Ej: un, rollo, saco', max_length=20, verbose_name='Unidad')),
                ('cantidad_por_produccion', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Cantidad por producción')),
                ('peso_envase_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Peso envase (kg)')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envases', to='fichas.fichapan')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sap', models.CharField(max_length=20, verbose_name='Código SAP')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('peso_producto_kg', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Peso producto (kg)')),
                ('cod_barra', models.CharField(blank=True, max_length=50, verbose_name='Código de barras')),
                ('cod_balanza', models.CharField(blank=True, max_length=50, verbose_name='Código balanza')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos_venta', to='fichas.fichapan')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Materia prima')),
                ('unidad', models.CharField(help_text='Ej: Kg, Lt, g', max_length=20, verbose_name='Unidad')),
                ('cantidad_receta', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Cantidad receta')),
                ('cantidad_batida', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Cantidad batida')),
                ('es_harina_base', models.BooleanField(default=False, verbose_name='¿Es la harina base?')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_primas', to='fichas.fichapan')),
            ],
        ),
    ]
