# Generated by Django 5.2.8 on 2025-11-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoHorneado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Ej: 1, 2, 3...', verbose_name='Orden del paso')),
                ('tiempo_min', models.PositiveIntegerField(verbose_name='Tiempo en minutos')),
                ('descripcion', models.CharField(help_text='Ej: 30 min con tiraje abierto', max_length=200, verbose_name='Descripción del paso')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_horneado', to='fichas.fichapan')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
