# Generated by Django 5.2.8 on 2025-11-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_pasohorneado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horneado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_inicial_c', models.PositiveIntegerField(help_text='Ej: 250', verbose_name='Temperatura inicial (°C)')),
                ('vapor_segundos', models.PositiveIntegerField(blank=True, help_text='Ej: 2 segundos', null=True, verbose_name='Vapor (segundos)')),
                ('temperatura_final_c', models.PositiveIntegerField(help_text='Ej: 180', verbose_name='Temperatura final (°C)')),
                ('tiempo_total_min', models.PositiveIntegerField(help_text='Ej: 30', verbose_name='Tiempo total (min)')),
                ('tiro', models.CharField(blank=True, help_text='Ej: tiro cerrado', max_length=50, verbose_name='Tiro (abierto/cerrado)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas adicionales de horneado')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horneado', to='fichas.fichapan')),
            ],
        ),
    ]
