# Generated by Django 5.2.8 on 2025-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_horneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapan',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='panes/'),
        ),
    ]
