# Generated by Django 5.2.8 on 2026-04-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_fichapan_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapan',
            name='codigo',
            field=models.CharField(help_text='Ej: 3514-D-PAN-058', max_length=30, unique=True, verbose_name='Código documento'),
        ),
    ]
