# Generated by Django 5.2.8 on 2026-04-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_alter_fichapan_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horneado',
            name='tiro',
            field=models.CharField(blank=True, help_text='Ej: tiro cerrado', max_length=200, verbose_name='Tiro (abierto/cerrado)'),
        ),
    ]
